# For more explanations, see: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024: false
