name: Release Docker
# From: https://github.com/Erikvl87/docker-languagetool/blob/de34895ebaaf6720970b8b3dd6b79d7330642154/.github/workflows/release.yml

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./docker-image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: docker build --target=build -t filesfinder-build .
      - name: Tag
        run: |
          echo 'DOCKER_TAG<<EOF' >> $GITHUB_ENV
          echo $(echo ${{ github.ref }} | grep -oP '(?<=refs/tags/v).*') >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_ACCESSTOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin     
      - name: Push to Docker Hub
        run: |
          docker buildx build --push \
            --tag $DOCKERHUB_REPOSITORY:$DOCKER_TAG \
            --tag $DOCKERHUB_REPOSITORY:latest \
            --platform linux/amd64,linux/arm64 .
        env:
          DOCKERHUB_REPOSITORY: jeertmans/filesfinder

